base:
  cuda: False
  seed: 1
  n_training_threads: 1
  n_rollout_threads: 1
  num_env_steps: 500


envs:
  env_name: simgle_lattice
  env_dim: 30
  dilemma_strength: 1.5
  initial_ratio: [0.5,0.5]

train:
  episode_length: 1
  K: 0.1 # Uncertainty by strategy adoptions
  log_interval: 10
